
---
title: "README"
output:
  html_document: default
  pdf_document: default
---
## Shiny App: Discrete Water Temperature & Specific Conductance (DiSCWT) processing tool

<br>

### Overview:

DiSCWT is a Shiny application that processes discrete SC and WT data from XML files generated by SVMobileAQ and formats the data for uploading to Aquarius samples. It reads XML data, extracts relevant parameters, and compiles cleaned data into the following output data frames: `qwsamples.txt` and `qwresults.txt`. 

<br>

The app is built in Rstudio using the following directory structure. Files can be accessed via the github repository:[DiSCWT](https://github.com/jpdarling/DiSCWT)

### Directory structure:
<br>

```
/project_directory
├── DiSCWT.Rproj          # RStudio Project file 
├── app.R                 # Main Shiny app script, defines the UI and server logic, and executes the app.
├── functions/            # Folder containing function scripts
│   ├── processing_functions.R  # Central script referencing most functions
│   ├── temp_processing.R       # Functions for temperature processing tasks
│   ├── sc_processing.R         # Functions for specific conductance processing tasks
│   └── time_processing.R       # Functions for datetime processing tasks
├── rsconnect/            # Folder for Shiny app deployment settings
│   └── shinyapps.io/           # Folder for app settings
│       └── discwt.dcf              # Deployment configuration file
├── test_xmls/            # Folder for input data used during app development
│   ├── SV_....xml              # Sample XML file for testing
│   └── ...                     # additional XML files as needed for testing.
├── README.Rmd            # Project documentation, r markdown
├── README.md             # Project documentation, markdown file for github
├── www/                  # Folder to store stratic files 
│   └── README.HTML             # Static HTML version of README for referencing within the app
└── deployApp.R                 # Script for deploying the app to shinyapps.io

```
<br>

### How to Use:
1.  Run the app on a shinyapps.io server:
    <https://discwt.shinyapps.io/discwt/> or download the file directory to run app.R from RStudio. 
2.  Select your field office. This will populate in the project_cd, for example "UT25MOAB".
3.  Batch upload SVMAQ XML files.
4.  Process the files and check for any issues printed in the processing log.
5.  Download `qwsample.txt` and `qwresult.txt` files.

<br>

### Notes on data formats and processing:

The tool identifies specific XML paths and uses regex patterns to capture information from XML comments, allowing for some variations in how the data may appear. There are inherent challenges to extracting data from varied comment formats. Below are some examples of XML comments with specific conductance, temperature and associated metadata data that the script successfully processes. If you wish to successfully use DiSCWT, you will need to follow the templates below for documenting specific conductance (SC), temperature, and associated metadata in SVMAQ comments.


####   Recongized formats for discharge measurement comments:

- ##### *`conductivity = 62 uS/cm 1 ft from lew 0.5 ft depth`*

- ##### *`sc = 1525 uS/cm middle channel 0.25 depth`*

- ##### *`spec cond = 1060 uS/cm 1 ft from lew, 0.28 ft depth`*

- ##### *`specific cond = 747 uS/cm 1 ft from lew 0.3 ft depth`*

- ##### *`sc: 335 2 ft from RB`*


####   Recongized formats for site visit comments:

- ##### *`...@ 10:53 sc = 230 uS/cm, WT = 13.2 deg C, from middle of channel width = 1.2 ft, and 0.4 ft depth`*

- ##### *`cond: 547 uS/cm, 32.1F, width =22 ft, 1 ft from loew 1 ft depth`*

- ##### *`...spec cond = 269 uS/cm, 5.5 deg, 1 ft from rew 0.5 ft depth.`*
    
- ##### *`...@ 0847 am WT = 8.3 deg C, SC = 308 uS/cm, 0.24 ft depth, middle of flume.`*

- ##### *`SC = 726, water temp = 4.8, time = 1255....`*

<br>

### Methods and workflow for extracting specific parameters from XML comments:

Many parameter values are derived from fields within the XML structure however sometimes the script must look elsewhere to extract data. Below is a summary of how the script operates to pull out data from unsupported XML comments associated with the various parameters: 

<br>

- #### Datetime:

    The script first attempts to pull the datetime field nested within the XML structure associated with the reading time of ADV verification temperature            readings. This time is most often associated with when specific data (such as SC and WT) is recorded.

    If this yields a NULL result, the script then search for time entered in the site visit comments. The script looks for time-related expressions using regex     patterns to recognize *`HH:mm`* or *`HMM`* values preceded by **`@`**, **`at`**, or **`time=`**. It also accounts for optional suffixes like **`am`**,        **`pm`**, **`mst`**, **`mdt`**, or **`hrs`**. If the regex successfully extracts a time from the site visit comments, it is combined with the date from the     XML's `StartDateTime` to form a complete datetime object. All times are assumed to be in local time (`"America/Denver"`).

    Times indicated with AM and PM are handled by following these rules:
    - If a time is in a 12-hour format with AM or PM, it will be converted to a 24-hour format (e.g., `"2:30 PM"` becomes `"14:30"`).
    - If no AM/PM is present, the time is assumed to be in 24-hour format.

<br>

- #### Measurement Depth (ft), Parameter 00003:

    The Measurement Depth is extracted from the comments associated with the discharge measurement or the site visit. The script first attempts to retrieve the measurement depth from the discharge measurement comments using a regular expression pattern that looks for numeric values associated with depth phrases, such as **`"1 ft depth"`** or **`"depth = 1 ft"`**. The regular expression pattern is case-insensitive to accommodate various capitalizations of the depth-related keywords. 

    If no depth value is found in the discharge measurements comments, the script then checks the site visit comment for any relevant depth information. This is also done using the same regular expression pattern, which searches for the depth mentioned with terms like **`"ft depth"`** or **`depth"`**.
    
<br>

-  #### Stream Width (ft), Parameter 00004: 

    The stream width for parameter 00004 is primarily extracted from the discharge measurement data. If a value is found, it is recorded and saved in the results. If no width is associated with the discharge measurement, the script looks for descriptions in the site visit comments, using regular expressions to capture numeric values associated with terms like **`"width"`** or **`"channel width"`**. If no width is found in either the discharge measurement or the site visit comments, the parameter is excluded from the final results. 

<br>

-  #### Distance from LEW (ft), Parameter 00009: 

    The distance from the left edge of water (LEW) is extracted from comments associated with either the discharge measurement or the site visit. A regular expression pattern captures the numeric distance from **`"LEW"`** or the right bank (**`"RB"`**). If the comment references the right bank (e.g., **`"RB"`**, **`"REW"`**), the value is adjusted by subtracting the distance from the stream width (parameter 00004) to report the distance from LEW. If the distance is referenced as being from the middle of the channel (e.g.,**`"mid channel"`**), the value is calculated as half of the stream width (parameter 00004).

    If no valid distance is found or if the required stream width is missing, the parameter is omitted from the final results.

<br>

-  #### Water Temperature (˚C), Parameter 00010: 

    The script first attempts to extract the verification water temperature and its unit from the XML structure associated with ADV measurements. If no temperature data is found, it searches the site visit comments for temperature values using regex patterns. The regex matches phrases such as **`"temp=8.3 deg C"`** or **`"WT = 32F"`**, and identifies temperature units of either **`"C"`** (Celsius) or **`"F"`**(Fahrenheit). 

    If no unit is found, the script defaults to Celsius (°C), and prints a message in the processing log. If the temperature is recorded in Fahrenheit (°F), the script converts the value to Celsius (°C) using the formula: `Celsius = (Fahrenheit − 32) × (5/9)`, and prints both the original Fahrenheit value and its converted Celsius value in the processing log. Only valid temperatures reported in Celsius are included in the final results.

<br>

-  #### Specific Conductance (μS/cm), Parameter 00095:

    The script extracts Specific Conductance (SC) data from comments associated with either the discharge measurement or the site visit. The regex pattern prioritizes matching **`"SC"`** values, checking for common patterns such as **`"SC = 308 uS/cm"`** or **`"SC: 500 uS"`**. If a valid SC value is found, it proceeds by extracting the numeric value and verifying the unit of **`"μS/cm"`** (microsiemens per centimeter). If no unit is specified, the function defaults to **`"μS/cm"`**, and a message is printed in the processing log. If non-standard units like "mS" or "ms" are found, a message indicates that conversion may be needed, and the unit is marked as invalid.

    If SC is not found, the script then searches for variations like **`"spec cond"`** or **`"specific cond"`** and follows the same process of extracting and validating the numeric value and unit. Similarly, if the script doesn't find patterns with **`"SC"`** or **`"spec cond"`**, it checks for terms like **`"conductivity"`** or **`"cond"`**, applying the same extraction and validation steps.

    In cases where conductivity values are used, the script converts these values to specific conductance at 25°C using a compensation factor of 0.0191 along with the temperature value associated with the reading. If no temperature value is provided, a warning is printed in the processing log, indicating that no adjustment was made and that the reading is marked as invalid.

<br>

####  Contact

For questions or feedback contact`jdarling@usgs.gov`.





